deployment:
  tasks:
    - export DEPLOYPATH=/home/tecnolab/webapp.tecnolabroma.it
    - /bin/rsync -av --exclude='.git' ./ $DEPLOYPATH
    - /bin/rsync -av ./public/ $DEPLOYPATH/public
    - cd $DEPLOYPATH
    - /usr/local/bin/php artisan config:clear
    - /usr/local/bin/php artisan cache:clear
    - /usr/local/bin/php artisan route:clear
    - /usr/local/bin/php artisan view:clear
    - /usr/local/bin/php artisan config:cache
    - /usr/local/bin/php artisan route:cache
    - /usr/local/bin/php artisan view:cache
    - /usr/local/bin/php artisan migrate --force
