deployment:
  tasks:
    - export DEPLOYPATH=/home/tecnolab/webapp.tecnolabroma.it
    # copia tutto tranne la cartella public
    - /bin/rsync -av --exclude='.git' --exclude='public' ./ $DEPLOYPATH
    # copia solo il contenuto di public dentro la public effettiva
    - /bin/rsync -av public/ $DEPLOYPATH/public
    - cd $DEPLOYPATH
    - /usr/local/bin/php artisan config:clear
    - /usr/local/bin/php artisan cache:clear
    - /usr/local/bin/php artisan route:clear
    - /usr/local/bin/php artisan view:clear
    - /usr/local/bin/php artisan config:cache
    - /usr/local/bin/php artisan route:cache
    - /usr/local/bin/php artisan view:cache
    - /usr/local/bin/php artisan migrate --force
